<%@ Page Language="VB" AutoEventWireup="false" CodeFile="XmlDataSourceXSLT.aspx.vb"
    Inherits="XmlDataSourceXSLT" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:XmlDataSource ID="sourceDVD" runat="server" DataFile="~/DvdList.xml"
            TransformFile="~/DVDTreeList.xsl"></asp:XmlDataSource>
    </div>
    <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False"
        DataSourceID="sourceDVD">
        <DataBindings>
            <asp:TreeNodeBinding DataMember="Movies" Text="Movies" Value="Movies" />
            <asp:TreeNodeBinding DataMember="DVD" TextField="Title" />
            <asp:TreeNodeBinding DataMember="Star" TextField="Name" />
        </DataBindings>
    </asp:TreeView>
    </form>
</body>
</html>
