<%@ Page Language="VB" AutoEventWireup="false" CodeFile="ObjectDataSourceInsert.aspx.vb" Inherits="ObjectDataSourceInsert" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        &nbsp;<asp:ObjectDataSource ID="sourceEmployees" runat="server" DataObjectTypeName="DatabaseComponent.EmployeeDetails"
            DeleteMethod="DeleteEmployee" InsertMethod="InsertEmployee" OldValuesParameterFormatString="original_{0}"
            SelectMethod="GetEmployees" TypeName="DatabaseComponent.EmployeeDB">
            <DeleteParameters>
                <asp:Parameter Name="employeeID" Type="Int32" />
            </DeleteParameters>
        </asp:ObjectDataSource>
            
        <asp:DetailsView ID="detailsInsertEmployee" runat="server" DataSourceID="sourceEmployees" DefaultMode="Insert"
         AutoGenerateInsertButton="True" AutoGenerateRows="False"
            Height="50px" Width="125px" CellPadding="4" 
            Font-Names="Verdana" Font-Size="Small" ForeColor="#333333" GridLines="None" >
            <footerstyle backcolor="#507CD1" font-bold="True" forecolor="White" />
            <commandrowstyle backcolor="#D1DDF1" font-bold="True" />
            <rowstyle backcolor="#EFF3FB" />
            <fieldheaderstyle backcolor="#DEE8F5" font-bold="True" />
            <pagerstyle backcolor="#2461BF" forecolor="White" horizontalalign="Center" />
            <Fields>                
                <asp:BoundField InsertVisible="False" DataField="EmployeeID" HeaderText="EmployeeID" SortExpression="EmployeeID" />
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                <asp:BoundField DataField="TitleOfCourtesy" HeaderText="TitleOfCourtesy" SortExpression="TitleOfCourtesy" />                
            </Fields>
            <headerstyle backcolor="#507CD1" font-bold="True" forecolor="White" />
            <editrowstyle backcolor="#2461BF" />
            <alternatingrowstyle backcolor="White" />
        </asp:DetailsView>
        
        <asp:Label ID="lblConfirmation" Font-Names="Verdana" Font-Size="Small" runat="server" EnableViewState="false"></asp:Label>
        <br /><br />
       
        <asp:GridView ID="gridEmployeeList" runat="server" DataSourceID="sourceEmployees" DataKeyNames="EmployeeID"
            CellPadding="4" Font-Names="Verdana" Font-Size="Small" ForeColor="#333333" 
            GridLines="None" AutoGenerateColumns="False" AutoGenerateDeleteButton="true"
            EnableSortingAndPagingCallbacks="True" PageSize="5" >
           
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <AlternatingRowStyle BackColor="White" />
            
            <Columns>                
                <asp:BoundField DataField="FirstName" HeaderText="FirstName" SortExpression="FirstName" />
                <asp:BoundField DataField="EmployeeID" InsertVisible="False" HeaderText="EmployeeID" SortExpression="EmployeeID" />
                <asp:BoundField DataField="LastName" HeaderText="LastName" SortExpression="LastName" />
                <asp:BoundField DataField="TitleOfCourtesy" HeaderText="TitleOfCourtesy" SortExpression="TitleOfCourtesy" />                
            </Columns>
        </asp:GridView>               &nbsp;
    
    </div>
    </form>
</body>
</html>
